// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwj06s_TY_VWFro-BGva_4BS7VAU5mwCw',
    appId: '1:782864367181:web:b45a730ba68f98ee782604',
    messagingSenderId: '782864367181',
    projectId: 'voice-car-esp-32',
    authDomain: 'voice-car-esp-32.firebaseapp.com',
    databaseURL: 'https://voice-car-esp-32-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'voice-car-esp-32.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB7qFlPbOzRwuL1hmvVwGhbLAiPsqfBkA',
    appId: '1:782864367181:android:c7dff41a1d82222b782604',
    messagingSenderId: '782864367181',
    projectId: 'voice-car-esp-32',
    databaseURL: 'https://voice-car-esp-32-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'voice-car-esp-32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCVgZ08szvVDSMSRs4HmRKlQqUs5GyaLU',
    appId: '1:782864367181:ios:fabb34ac48c40684782604',
    messagingSenderId: '782864367181',
    projectId: 'voice-car-esp-32',
    databaseURL: 'https://voice-car-esp-32-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'voice-car-esp-32.appspot.com',
    iosBundleId: 'com.example.esp32VoiceCar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCVgZ08szvVDSMSRs4HmRKlQqUs5GyaLU',
    appId: '1:782864367181:ios:39e1aad21279c2d9782604',
    messagingSenderId: '782864367181',
    projectId: 'voice-car-esp-32',
    databaseURL: 'https://voice-car-esp-32-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'voice-car-esp-32.appspot.com',
    iosBundleId: 'com.example.esp32VoiceCar.RunnerTests',
  );
}
